// One-off data acquisition: top US places by % Asian Indian (alone or in any combination).
//
// Source: U.S. Census Bureau ACS 5-year estimates, 2023 vintage.
// Table B02018 "Asian Alone or in Any Combination by Selected Groups".
// Variable B02018_021E = "South Asian: Asian Indian" (alone or in combination).
// Variable B01003_001E = total population.
//
// Run:  node scripts/fetch_places.mjs > /tmp/places.json
//       — or paste the printed JS literal directly into index.html.
//
// Census API is unkeyed (rate-limited at 500 requests/day per IP). We make 51 calls.

const STATES = [
  ["01", "Alabama"], ["02", "Alaska"], ["04", "Arizona"], ["05", "Arkansas"],
  ["06", "California"], ["08", "Colorado"], ["09", "Connecticut"], ["10", "Delaware"],
  ["11", "District of Columbia"], ["12", "Florida"], ["13", "Georgia"], ["15", "Hawaii"],
  ["16", "Idaho"], ["17", "Illinois"], ["18", "Indiana"], ["19", "Iowa"],
  ["20", "Kansas"], ["21", "Kentucky"], ["22", "Louisiana"], ["23", "Maine"],
  ["24", "Maryland"], ["25", "Massachusetts"], ["26", "Michigan"], ["27", "Minnesota"],
  ["28", "Mississippi"], ["29", "Missouri"], ["30", "Montana"], ["31", "Nebraska"],
  ["32", "Nevada"], ["33", "New Hampshire"], ["34", "New Jersey"], ["35", "New Mexico"],
  ["36", "New York"], ["37", "North Carolina"], ["38", "North Dakota"], ["39", "Ohio"],
  ["40", "Oklahoma"], ["41", "Oregon"], ["42", "Pennsylvania"], ["44", "Rhode Island"],
  ["45", "South Carolina"], ["46", "South Dakota"], ["47", "Tennessee"], ["48", "Texas"],
  ["49", "Utah"], ["50", "Vermont"], ["51", "Virginia"], ["53", "Washington"],
  ["54", "West Virginia"], ["55", "Wisconsin"], ["56", "Wyoming"],
];

const POP_FLOOR = 5000;
const TOP_N = 200;

// "Cupertino city, California" -> "Cupertino"
// "Edison township, New Jersey" -> "Edison"
// "Reston CDP, Virginia" -> "Reston"
function cleanName(raw) {
  // Strip ", State"
  let s = raw.replace(/,.*$/, "");
  // Strip common suffixes
  s = s.replace(/\s+(city|town|township|village|borough|CDP|municipality|consolidated government|metro government|metropolitan government|unified government|urban county|comunidad|zona urbana)$/i, "");
  // Some entries have "Village of" or "City of" prefixes (rare)
  s = s.replace(/^(Village of |City of |Town of )/i, "");
  return s.trim();
}

async function fetchState([fips, name]) {
  const url = `https://api.census.gov/data/2023/acs/acs5?get=NAME,B02018_021E,B01003_001E&for=place:*&in=state:${fips}`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`${name} (${fips}): ${res.status} ${res.statusText}`);
  }
  const rows = await res.json();
  // First row is headers
  const out = [];
  for (let i = 1; i < rows.length; i++) {
    const [rawName, indianStr, popStr] = rows[i];
    const population = parseInt(popStr, 10);
    const indian = parseInt(indianStr, 10);
    if (!Number.isFinite(population) || population < POP_FLOOR) continue;
    if (!Number.isFinite(indian) || indian <= 0) continue;
    out.push({
      name: cleanName(rawName),
      state: name,
      population,
      pctIndian: +(indian / population).toFixed(4),
    });
  }
  return out;
}

async function main() {
  console.error(`Fetching ${STATES.length} states (population floor ${POP_FLOOR}, top ${TOP_N})...`);
  const all = [];
  for (const s of STATES) {
    try {
      const places = await fetchState(s);
      all.push(...places);
      console.error(`  ${s[1].padEnd(22)} → ${places.length} places`);
    } catch (e) {
      console.error(`  ${s[1].padEnd(22)} → ERROR: ${e.message}`);
    }
  }
  all.sort((a, b) => b.pctIndian - a.pctIndian);
  const top = all.slice(0, TOP_N);
  console.error(`\nTotal qualifying places: ${all.length}`);
  console.error(`Top ${top.length} cutoff: ${(top[top.length - 1].pctIndian * 100).toFixed(2)}% Asian Indian`);
  console.error(`Top 5:`);
  top.slice(0, 5).forEach((p, i) => console.error(`  ${i + 1}. ${p.name}, ${p.state} — ${(p.pctIndian * 100).toFixed(1)}% (pop ${p.population.toLocaleString()})`));

  // Emit JS literal to stdout
  console.log(`// Auto-generated by scripts/fetch_places.mjs. Source: U.S. Census ACS 5-year 2023, table B02018.`);
  console.log(`// Variable B02018_021E ("Asian Indian" alone or in combination) / B01003_001E (total population).`);
  console.log(`// Population floor ${POP_FLOOR}; top ${TOP_N} by % Asian Indian.`);
  console.log(`const PLACES = [`);
  for (const p of top) {
    console.log(`  { name: ${JSON.stringify(p.name)}, state: ${JSON.stringify(p.state)}, population: ${p.population}, pctIndian: ${p.pctIndian} },`);
  }
  console.log(`];`);
}

main().catch(e => { console.error(e); process.exit(1); });
